pipeline {
    agent any

    environment {
        DOCKER_IMAGE_BACKEND = "notes-backend"
        DOCKER_IMAGE_FRONTEND = "notes-frontend"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Snehamaturu-123/notes-app.git'
            }
        }

        stage('Build Backend Docker') {
            steps {
                sh 'docker build -t notes-backend ./backend'
            }
        }

        stage('Build Frontend Docker') {
            steps {
                sh 'docker build -t notes-frontend ./frontend'
            }
        }

        stage('Run Containers') {
            steps {
                sh '''
                # Create network if not exists
                docker network create notes-net || true

                # Run MongoDB
                docker run -d --name notes-mongo --network notes-net mongo:6

                # Run Backend (port 5000)
                docker run -d --name notes-backend --network notes-net -p 5000:5000 notes-backend

                # Run Frontend (port 8082)
                docker run -d --name notes-frontend --network notes-net -p 8082:80 notes-frontend
                '''
            }
        }
    }
}
