version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: notes-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notesdb
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    image: notes-backend   # <-- Add this
    container_name: notes-backend
    ports:
      - "5000:5000"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/notesdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: notes-frontend   # <-- Add this
    container_name: notes-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  mongo-data:
